### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by farhan-syah** [open-hr/core#1]
- [ ] **Is the product working properly?**
- [ ] **Is the features under MVP feature list completed?**
- [ ] **Have security vulnerabilities been remediated?**
- [ ] **Are instructions for contributing included (`CONTRIBUTING.md`)?**
- [ ] **Are installation instructions clearly written in the `README` _and_ tested on a clean machine?**
- [ ] **Are all dependencies described in the `README`**
- [ ] **Are the API docs generated?**
- [ ] **Are there unit tests?**
- [ ] **If applicable and possible, is it set up in TravisCI?**
- [ ] **Have multiple people reviewed the code?**
- [ ] **Is there a screenshot in the `README`, if applicable?**
